# Generated by Django 6.0 on 2025-12-27 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
